calculate the sum of the postings

sum quantity by commodity for each transaction
-----
select
    row_number() over (partition by transaction_no order by tc_commodity) as num,
    transaction_no,
    tc_commodity,
    -1.0*sum(tc_quantity) as tc_quantity_sum
from
    postings
where
    tc_commodity is not null
group by
    transaction_no, tc_commodity
order by
    transaction_no, tc_commodity


find the unbalanced transactions
----
select
    num,
    transaction_no,
    tc_commodity,
    tc_quantity_sum
from
    [transactions_grouped_by_commodity]
where
    num = 1 and tc_quantity_sum <> 0
order by
    transaction_no


create the final postings table

select
    a.statement_no
    a.transaction_no,
    a.account,
    coalesce(a.cp_commodity, b.tc_commodity) as cp_commodity,
    coalesce(a.cp_quantity, b.tc_quantity_sum) as cp_commodity,
    coalesce(a.tc_commodity, b.tc_commodity) as tc_commodity,
    coalesce(a.tc_quantity, b.tc_quantity_sum) as tc_quantity
from
    postings a
left join
    [unbalanced transactions] b
on
    a.transaction_no = b.transaction_no
order by
    a.transaction_no, a.statement_no


get the errors in the final postings
-----
select
    transaction_no,
    tc_commodity,
    sum(tc_quantity) as tc_quantity_sum
from
    [final postings]
group by
    transaction_no, tc_commodity
having
    sum(tc_quantity) <> 0
order by
    transaction_no, tc_commodity



    