[package]
name = "ledger-rs-csv"
version = "0.1.0"
edition = "2024"

[dependencies]
ledger-rs-core = { path = "../ledger-rs-core" }
chrono = { version = "0.4.40", features = ["serde"] }
csv = "1.3.1"
rust_decimal = "1.37.1"
serde = { version = "1.0.219", features = ["derive", "serde_derive"] }
